# Generated by Django 3.2 on 2021-11-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_places_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
