# Generated by Django 3.2 on 2021-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_places_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=256, unique=True, verbose_name='адрес доставки'),
        ),
    ]
