# Generated by Django 3.2 on 2021-10-14 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20211013_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
    ]
