# Generated by Django 3.2 on 2021-10-14 02:11

from django.db import migrations


def count_cost_for_old_orders(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')

    orders = Order.objects.all()
    for order in orders:
        order_products = order.order.all()
        for order_product in order_products:
            order_product.cost = order_product.quantity * order_product.product.price
            order_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderedproduct_cost'),
    ]

    operations = [
        migrations.RunPython(count_cost_for_old_orders),
    ]
