# Generated by Django 3.2 on 2021-10-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20211014_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обработанный'), ('unprocessed', 'Необработанный')], default='unprocessed', max_length=12, verbose_name='статус заказа'),
        ),
    ]
