# Generated by Django 3.2 on 2021-10-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commentary',
            field=models.CharField(blank=True, max_length=256, verbose_name='комментарий'),
        ),
    ]
