# Generated by Django 3.2 on 2021-11-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_orderedproductcost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedProductCost',
        ),
    ]
