# Generated by Django 3.2 on 2021-12-02 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_orderedproduct_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='общая стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=256, verbose_name='описание'),
        ),
    ]
